name: Notify prod plan warning

on:
  issue_comment:
    types: [created]

jobs:
  notify-prod-plan-warning:
    # plan結果のプロジェクト数が1つと複数の場合でメッセージ形式が微妙に異なるので両方に対応している
    if: |
      github.event.issue.pull_request &&
      ((contains(github.event.comment.body, 'Ran Plan for ') &&
        contains(github.event.comment.body, '1. project: `prod')) ||
       contains(github.event.comment.body, 'Ran Plan for project: `prod'))
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Post prod plan warning comment
        uses: actions/github-script@v7
        with:
          script: |
            const warning = "⚠️ prod環境の変更が行われる可能性があります。\n⚠️ applyするタイミングはチームリーダーに確認してください。";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: warning,
            });
