name: Checkout test by push event
on:
  push:
    branches: [ "**" ]

jobs:
  checkout_test:
    name: checkout test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Show variables
        run: |
          echo "01 GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "02 GITHUB_REF=${GITHUB_REF}"
          echo "03 GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "04 GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "05 GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "06 GITHUB_SHA=${GITHUB_SHA}"
          echo "07 github.event.pull_request.head.ref"=${{ github.event.pull_request.head.ref }}
          echo "08 github.event.pull_request.head.sha"=${{ github.event.pull_request.head.sha }}
          echo "09 github.event.pull_request.base.ref"=${{ github.event.pull_request.base.ref }}
          echo "10 github.event.pull_request.base.sha"=${{ github.event.pull_request.base.sha }}
      - uses: actions/checkout@v4
      - name: Show current commit hash
        run: |
          git log -n 1 --format=%H
          git log



